# Generated by Django 5.1.5 on 2025-02-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintainace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
