# Generated by Django 5.1.5 on 2025-02-09 00:22

import maintainace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintainace', '0002_maintenancerequest_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='maintenance_attachments/', validators=[maintainace.models.validate_file_extension]),
        ),
    ]
