# Generated by Django 5.1.5 on 2025-02-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_onetimepassword_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='used',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
