# Generated by Django 5.1.5 on 2025-02-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_onetimepassword_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Landlord', 'Landlord'), ('Tenant', 'Tenant'), ('Admin', 'Admin')], default='Tenant', max_length=16),
        ),
    ]
