# Generated by Django 5.1.5 on 2025-02-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
